OSV/Controllers/SheetViewController.cs
using OSV.Models;
using System;
using System.Collections.Generic;
using System.Data.Linq.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OSV.Controllers
{
    public class SheetViewController : Controller
    {
        private readonly DB db = new DB();
        // GET: SheetView
        public ActionResult Index()
        {
            try
            {
                List<string> paperCodes = db.tblPaperMasters.Select(s => s.PaperCode).Distinct().ToList();
                ViewBag.PaperCodes = paperCodes;
                List<string> Centers = db.tblOMRDatas.Select(x => x.CenterCode).Distinct().ToList();
                ViewBag.Centers = Centers;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                ViewBag.PaperCodes = new List<string>();
                ViewBag.Centers = new List<string>();
            }
            return View();
        }

        public ActionResult UndetectedNumbers()
        {
            try
            {
                List<string> paperCodes = db.tblPaperMasters.Select(s => s.PaperCode).Distinct().ToList();
                ViewBag.PaperCodes = paperCodes;
                List<string> Centers = db.tblOMRDatas.Select(x => x.CenterCode).Distinct().ToList();
                ViewBag.Centers = Centers;
                List<string> RollNumbers = db.tblOMRDatas.Where(x => x.RollNo.Contains("X")).Select(x => x.RollNo).ToList();
                ViewBag.RollNumbers = RollNumbers;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                ViewBag.PaperCodes = new List<string>();
                ViewBag.Centers = new List<string>();
                ViewBag.RollNumbers = new List<string>();
            }
            return View();
        }

        // GET: SheetView/GetSheet?5
        public JsonResult GetSheet(string paperCode, string centerCode, string RollNo)
        {
            var detail = db.tblOMRDatas
                .Where(x => x.CenterCode == centerCode && x.PaperCode == paperCode && x.RollNo == RollNo)
                .Select(s => new { s.FirstPageFile, s.SecondPageFile, s.MarksDetail }).FirstOrDefault();
            if (detail != null)
            {
                string path1 = $"{paperCode}/{centerCode}/{detail.FirstPageFile}";
                string path2 = $"{paperCode}/{centerCode}/{detail.SecondPageFile}";

                List<string> Files = new List<string>
                {
                    GetBase64(path1),
                    GetBase64(path2)
                };

                return Json(new { Files, detail.MarksDetail }, JsonRequestBehavior.AllowGet);
            }
            return Json(new List<string>(), JsonRequestBehavior.AllowGet);
        }

        private string GetBase64(string Path)
        {
            string SourceFilePath = System.Configuration.ConfigurationManager.AppSettings["SourceFilePath"];//.Replace(@"//", "*");
            Path = System.IO.Path.Combine(SourceFilePath + Path);
            string base64String;

            using (System.Net.WebClient client = new System.Net.WebClient())
            {
                using (MemoryStream m = new MemoryStream(client.DownloadData(Path)))
                {
                    using (Image image = Image.FromStream(m))
                    {
                        try
                        {
                            int imageWidth = 700;
                            int imageHeight = (int)((float)image.Height / (float)image.Width * imageWidth);
                            Image resizedImage = new Bitmap(imageWidth, imageHeight);

                            Graphics gfx = Graphics.FromImage(resizedImage);
                            gfx.DrawImage(image, 0, 0, imageWidth, imageHeight);
                            using (MemoryStream msResized = new MemoryStream())
                            {
                                resizedImage.Save(msResized, System.Drawing.Imaging.ImageFormat.Jpeg);
                                // Convert byte[] to Base64 String
                                base64String = Convert.ToBase64String(msResized.ToArray());
                            }

                            return base64String;
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine(e.Message);
                            return e.Message;
                        }
                    }
                }
            }
        }
    }
}

OSV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OSV</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
    @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sheet Viewer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View Sheets", "Index", "SheetView")</li>
                    <li>@Html.ActionLink("Ambigous Roll Numbers", "UndetectedNumbers", "SheetView")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Developed by HCS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>